In [6]:
import numpy as np

#### Задана матриця:

In [7]:
task_array = [[ 1,  9, 10,  8,  7,  7,  4, 4,  9,  6,  5,  2],
              [ 6,  9, 10,  8,  7,  9,  4,  4,  9,  7,  6, 10],
              [ 1,  7,  4 , 8,  6, 7,  4,  4,  2,  4,  1,  2 ],
              [ 1, 4 , 4 , 7 , 3 , 7, 2,  4,  2,  4,  1,  2 ],
              [ 1,4  ,4,  2  ,3,  1,  2,  3,  2,  4,  1,  2 ],
[ 5,  9 , 4,  2,  3,  8 , 2,  5  ,9,  9 , 5, 10 ],
[ 1,  4 , 4, 2,  3,  3  ,2 , 4  ,2  ,4  ,1 , 2 ],
[ 1,  3 , 2,  2,  3,  3 , 2,  4 , 2  ,4 , 1,  2 ],
[ 10,  9, 10,  8,  7,  9,  4,  4,  9 ,10,  9, 10 ],
[10 , 9, 10,  8,  7,  9,  5 , 4,  9 ,10,  9 ,10 ],
[ 1,  2,  2,  2,  3,  3,  2 , 4,  2 , 4,  1 , 2 ],
[ 1,  8,  6,  6,  3,  9,  7 , 7,  3 , 4,  1 , 8 ],
[1,  1,  3,  6,  3 , 7 , 2  ,3 , 2  ,4 , 1  ,2 ],
[1,  1,  3,  2,  3 , 3 , 1  ,1 , 2  ,4 , 1  ,2 ],
[ 1,  1,  2,  2,  3,  3,  1 , 1,  2 , 3,  1 , 2 ],
[ 3,  3,  8,  5, 10,  3,  3 , 3,  7 , 8,  1 , 8 ],
[10,  7, 10,  9, 10,  7,  8 , 4,  7 , 8,  3 , 8 ],
[10,  7, 10,  9, 10,  7,  8 , 4, 10 , 9,  3 , 9 ],
[ 4,  6,  2,  2,  3,  7,  2 , 2,  9 , 3,  3 , 8 ],
[ 1,  4,  2,  2,  2,  7,  1 , 1,  5 , 3,  3 , 8 ]]

In [8]:
#### Формування множини векторів сигма

In [9]:
#виконуємо порівняння двох альтернатив
def compareAlternatives ( a1, a2):
    comparisonResult = np.arange(len(a1))
    for i in range(0, len(a1)):
        if a1[i] > a2[i]:
            comparisonResult[i] = 1
            continue
        elif a1[i] < a2[i]:
            comparisonResult[i] = -1
            continue
        elif a1[i] == a2[i]:
            comparisonResult[i] = 0
    return comparisonResult

#формуємо множину векторів сигма попарним порівнянням альтернатив
def createSigmaVectors(matrix):
    alternatives = np.array(matrix)
    resultMatrix = [[0]*20 for i in range(20)]
    for i in range(0, 20):
        for j in range(0, 20):
            resultMatrix[i][j] = compareAlternatives(alternatives[i], alternatives[j])
    return resultMatrix

s_v = createSigmaVectors(task_array)
s_v

[[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([-1,  0,  0,  0,  0, -1,  0,  0,  0, -1, -1, -1]),
  array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0]),
  array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0]),
  array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
  array([-1,  0,  1,  1,  1, -1,  1, -1,  0, -1,  0, -1]),
  array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0]),
  array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0]),
  array([-1,  0,  0,  0,  0, -1,  0,  0,  0, -1, -1, -1]),
  array([-1,  0,  0,  0,  0, -1, -1,  0,  0, -1, -1, -1]),
  array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0]),
  array([ 0,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1]),
  array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0]),
  array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
  array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
  array([-1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1]),
  array([-1,  1,  0, -1, -1,  0, -1,  0,  1, -1,  1, -1]),
  array([-1,  1,  0, -1, -1,  0, -1,  0, -1, -1,  1, -1]),
  array([-1,  1,  1,  1,  1,  0,  1,  1,  0,  1,  1, -1]),

#### Максимальні та найбільші за P та R 
## a також допоміжні функції (визначення симетричної, асиметричної, непорівнюваної частин)

In [10]:
#отримати симетричну частину
def I(r):
    return (r==r.T)*r
#отримати асиметричну частину
def P(r):
    return r-I(r)

#отримати відношення непорівнюваності
def N(r):
    return (r==r.T)-I(r)

#Оптимізація за домінуванням найбільші по Р
def getDominationMaxOfP(m):
    matrix = np.array(m)
    max_ = []
    for i in range(0, len(matrix)):
        if matrix[i][i]==0 and matrix[i].sum()==len(matrix)-1:
            max_.append(i+1)
    return max_

#Оптимізація за домінуванням найбільші по R
def getDominationMaxOfR(m):
    matrix = np.array(m)
    max_ = []
    strong_max = []
    for i in range(0, len(matrix)):
        if matrix[i].sum()==len(matrix):
            max_.append(i+1)
            if matrix[:,i].sum()==1:
                strong_max.append(i+1)
    return max_, strong_max

#Оптимізація за блокуванням максимальні по Р
def getBlockingMaxP(m):
    matrix = np.array(m)
    max_ = []
    for i in range(0, len(matrix)):
        if matrix[:,i].sum()==0:
            max_.append(i+1)
    return max_

#Оптимізація за блокуванням максимальні по R
def getBlockingMaxR(m):
    matrix = np.array(m)
    sym = I(matrix)
    max_ = []
    strongMax = []
    for i in range(0, len(matrix)):
        if np.any(np.array_equal(matrix[:,i], sym[:,i])==False)==False:
            max_.append(i+1)
            if matrix[:,i].sum()==1 and matrix[i][i]==1:
                strongMax.append(i+1)
    return max_, strongMax
    
#перевірка на симетричність
def checkIsSymetric(matrix):
    sym = I(np.array(matrix))
    flag = False
    for i in range(0, len(sym)):
        if sym[i].sum()>0:
            flag = True
            break
    return flag

#виведення найбільших/максимальних елементів
def printMaxElements(matrix):
    #якщо симетрична частиа наявна - найбільші та максимальні по R
    if checkIsSymetric(matrix):
        m, sm = getDominationMaxOfR(matrix)
        if len(m)>0:        
            print("Найбільші за R: {}".format(m))
            print("Строго найбільші за R: {}".format(sm))
        else:
            m, sm = getBlockingMaxR(matrix)
            print("Максимальні за R: {}".format(m))
            print("Строго максимальні за R: {}".format(sm))
    #якщо симетрична частина відсутня - найбільші та максимальні по Р
    else:
        if len(getDominationMaxOfP(matrix))>0:
            print("Найбільший за Р: {}".format(getDominationMaxOfP(matrix)))
        else:
            print("Максимальні за Р: {}".format(getBlockingMaxP(matrix)))

#### Відношення Парето

In [11]:
def paretoCheckVector(vector):
    check = np.array(vector)
    flag = True
    for i in range (0, len(check)):
        #усі елементи сигма-вектора невід'ємні
        if check[i]>=0:
            pass
        else:
            flag = False
    if flag:
        return 1
    else:
        flag = True
        for i in range (0, len(check)):
            #усі елементи сигма-вектора недодатні
            if check[i]<=0:
                pass
            else:
                flag = False
        if flag:
            return 2
        else:
            #сигма вектор містить як від'ємні, так і невід'ємні компоненти
            return 3
    
def paretoRelation(sigma_vectors):
    vectorsMatrix = np.array(sigma_vectors)
    resultMatrix = [[0]*20 for i in range(20)]
    for i in range(0, 20):
        resultMatrix[i][i] = 1
    for i in range(0, len(vectorsMatrix)):
        for j in range(i+1, len(vectorsMatrix)):
            flag = paretoCheckVector(vectorsMatrix[i][j])
            # якщо елементи вектора невід'ємні - пара альтернатив належить відношенню, симетрична не належить
            if flag == 1:
                resultMatrix[i][j] = 1
                resultMatrix[j][i] = 0
                continue
            # якщо елементи вектора недодатні - пара альтернатив не належить відношенню, симетрична належить
            elif flag == 2:
                resultMatrix[i][j] = 0
                resultMatrix[j][i] = 1
                continue
            # інакше відношення та симетричне йому не належать множині
            elif flag == 3:
                resultMatrix[i][j] = 0
                resultMatrix[j][i] = 0   
    f = open("task1.txt", "w")
    f.write(" 1" + '\n')
    for i in range(0,len(resultMatrix)):
        for j in range(0,len(resultMatrix)):
            f.write(" {} ".format(resultMatrix[i][j]))
        f.write('\n')
    f.close()
    return resultMatrix


printMaxElements(paretoRelation(s_v))
paretoRelation(s_v)

Максимальні за R: [6, 10, 12, 18]
Строго максимальні за R: [6, 10, 12, 18]


[[1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,

#### Мажоритарне відношення

In [12]:
def majorityRelation(sigma_vectors):
    vectorsMatrix = np.array(sigma_vectors)
    resultMatrix = [[0]*20 for i in range(20)]
    for i in range(0,len(vectorsMatrix)):
        for j in range (i,len(vectorsMatrix)):
            # якщо сума елементів сигма-вектора > 0 - пара альтернатив належить відношенню, симетричне не належить 
            if vectorsMatrix[i][j].sum()>0:
                resultMatrix[i][j]=1
                resultMatrix[j][i]=0
                continue
            # якщо сума елементів сигма-вектора < 0 - пара альтернатив не належить відношенню, симетрична належить
            elif vectorsMatrix[i][j].sum()<0:
                resultMatrix[i][j]=0
                resultMatrix[j][i]=1
                continue
            # якщо сума елементів сигма-вектора = 0 - пара альтернатив та симетричне ій не належать відношенню 
            elif vectorsMatrix[i][j].sum()==0:
                resultMatrix[i][j]=0
                resultMatrix[j][i]=0
    f = open("task2.txt", "w")
    f.write(" 2" + '\n')
    for i in range(0,len(resultMatrix)):
        for j in range(0,len(resultMatrix)):
            f.write(" {} ".format(resultMatrix[i][j]))
        f.write('\n')
    f.close()
    return resultMatrix

printMaxElements(majorityRelation(s_v))
majorityRelation(s_v)

Найбільший за Р: [10]


[[0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
 [1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
 [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,

#### Лексикографічне відношення

In [13]:
#k4>k11>k3>k9>k5>k1>k7>k2>k12>k10>k6>k8

# строге впорядкування критеріїв у векторі відповідно до варіанту
def sortStrongOrder(a):
    ordered = np.arange(len(a))
    order = np.array([ 3,10,2,8,4,0,6,1,11,9,5,7])
    for i in range (0, len(a)):
        ordered[i]=a[order[i]]
    return ordered

# впорядкування критеріїв у всіх векторах
def sortAllSigmaVectors(sigma_vectors):
    vectorMatrix = np.array(sigma_vectors)
    sortedMatrix = [[0]*20 for i in range(20)]
    for i in range(0,len(vectorMatrix)):
        for j in range(0,len(vectorMatrix)):
            sortedMatrix[i][j] = sortStrongOrder(vectorMatrix[i][j])
    return sortedMatrix

def lexicographicRelation(matrix):
    sortedVectors = np.array(matrix)
    resultMatrix = [[0]*20 for i in range(20)]
    for i in range (0, len(resultMatrix)):
        resultMatrix[i][i]=0
    for i in range(0, len(sortedVectors)):
        for j in range(i+1, len(sortedVectors)):
            # Розглядаємо сигма-вектор для пари альтернатив ai aj
            a = sortedVectors[i][j]
            for k in range(0, len(a)):
                # якщо ai переважає aj за критерієм k, пара ai aj належить відношенню, симетрична не належить
                if a[k]==1:
                    resultMatrix[i][j]=1
                    resultMatrix[j][i]=0
                    break
                # якщо aj переважає ai за критерієм k, пара ai aj не належить відношенню, симетрична належить
                elif a[k]==-1:
                    resultMatrix[i][j]=0
                    resultMatrix[j][i]=1
                    break
                # якщо альтернативи рівні за критерієм, переходимо до менш важливого критерію
                else:
                    continue
    f = open("task3.txt", "w")
    f.write(" 3" + '\n')
    for i in range(0,len(resultMatrix)):
        for j in range(0,len(resultMatrix)):
            f.write(" {} ".format(resultMatrix[i][j]))
        f.write('\n')
    f.close()
    return resultMatrix

printMaxElements(lexicographicRelation(sortAllSigmaVectors(s_v)))
lexicographicRelation(sortAllSigmaVectors(s_v))
            

Найбільший за Р: [18]


[[0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,

#### Відношення Березовського

In [22]:
#{k1,k3,k6} < {k9,k10} < {k2,k4,k5,k7,k8,k11,k12}

#
def setVectors(a):
        select1 = np.array([ 0, a[1], 0, a[3], a[4], 0, a[6], a[7], 0, 0, a[10], a[11]])
        select2 = np.array([ 0, 0, 0, 0, 0, 0, 0, 0, a[8], a[9], 0, 0]) 
        select3 = np.array([ a[0], 0, a[2], 0, 0, a[5], 0, 0, 0, 0, 0, 0])
        return select1, select2, select3

def divideVectorsIntoClasses(sigma_vectors):
    vectorsMatrix = np.array(sigma_vectors)
    class1Matrix = [[0]*20 for i in range(20)]
    class2Matrix = [[0]*20 for i in range(20)]
    class3Matrix = [[0]*20 for i in range(20)]
    for i in range(0,20):
        for j in range(0,20):
            a = vectorsMatrix[i][j]
            class1Matrix[i][j], class2Matrix[i][j], class3Matrix[i][j] = setVectors(a)      
        
    return class1Matrix, class2Matrix, class3Matrix

def berezovskiyRelation(sigma_vectors):
    # Pb1, Ib1, Nb1
    iter1_p = [[0]*20 for i in range(20)]
    iter1_i = [[0]*20 for i in range(20)]
    iter1_n = [[0]*20 for i in range(20)]
    # Pb2 (результуюче відношення)
    result_matrix = [[0]*20 for i in range(20)]
    # розбиваємо критерії на класи. с1 - найменш важливий
    c1,c2,c3=divideVectorsIntoClasses(s_v)
    pareto1 = np.array(paretoRelation(c1))
    pareto2 = np.array(paretoRelation(c2))
    pareto3 = np.array(paretoRelation(c3))
    # виділяємо для кожного класу симетричну, асиметричну та непорівнювану частини відношення Парето
    # I01, P01, N01 (приймаємо за Ib0, Pb0, Nb0)
    i1 = I(pareto1)
    p1 = P(pareto1)
    n1 = N(pareto1)
    # I02, P02, N02
    i2 = I(pareto2)
    p2 = P(pareto2)
    n2 = N(pareto2)
    #I03, P03, N03
    i3 = I(pareto3)
    p3 = P(pareto3)
    n3 = N(pareto3)
    
    # Формуємо Pb1, Ib1, Nb1
    for i in range(0,len(result_matrix)):
        for j in range(0, len(result_matrix)):
            if p2[i][j]==1 and p2[i][j]==p1[i][j]:
                iter1_p[i][j]=1            
            if p2[i][j]==1 and p2[i][j]==n1[i][j]:
                iter1_p[i][j]=1            
            if i2[i][j]==1 and i2[i][j]==p1[i][j]:
                iter1_p[i][j]=1
            if p2[i][j]==1 and p2[i][j]==i1[i][j]:
                iter1_p[i][j]=1
            if i2[i][j]==1 and i2[i][j]==i1[i][j]:
                iter1_i[i][j]=1 
    for i in range(0,len(result_matrix)):
        for j in range(0, len(result_matrix)):
            if iter1_p[i][j]==0 and iter1_i[i][j]==0:
                iter1_n[i][j]==1
    # Формуємо Pb2 (результат) порівнюючи I03, P03, N03 з Pb1, Ib1, Nb1
    for i in range(0,len(result_matrix)):
        for j in range(0, len(result_matrix)):
            if p3[i][j]==1 and p3[i][j]==iter1_p[i][j]:
                result_matrix[i][j]=1            
            if p3[i][j]==1 and p3[i][j]==iter1_n[i][j]:
                result_matrix[i][j]=1            
            if i3[i][j]==1 and i3[i][j]==iter1_p[i][j]:
                result_matrix[i][j]=1
            if p3[i][j]==1 and p3[i][j]==iter1_i[i][j]:
                result_matrix[i][j]=1  
    f = open("task4.txt", "w")
    f.write(" 4" + '\n')
    for i in range(0,len(result_matrix)):
        for j in range(0,len(result_matrix)):
            f.write(" {} ".format(result_matrix[i][j]))
        f.write('\n')
    f.close()
    return result_matrix

printMaxElements(berezovskiyRelation(s_v))
berezovskiyRelation(s_v)

Максимальні за Р: [9, 10, 18]


[[0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1],
 [1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,

#### Відношення Подиновського

In [23]:
# сортування значень критеріїв за спаданням
def psiAlternatives(matrix):
    alternatives = np.array(matrix)
    for i in range(0,20):
        a=alternatives[i]
        a[::-1].sort()
        alternatives[i] = a
    return alternatives

def podynovskiyRelation(matrix):
    # формування множини функції псі від альтернатив(сортування за спаданням)
    psi_a = psiAlternatives(matrix)
    # формування сигма-векторів побудованих для псі(аі)
    sv = createSigmaVectors(psi_a)
    # відношення Парето для множини псі(аі)
    resultMatrix = paretoRelation(sv)   
    f = open("task5.txt", "w")
    f.write(" 5" + '\n')
    for i in range(0,len(resultMatrix)):
        for j in range(0,len(resultMatrix)):
            f.write(" {} ".format(resultMatrix[i][j]))
        f.write('\n')
    f.close()
    return resultMatrix

printMaxElements(podynovskiyRelation(task_array))
podynovskiyRelation(task_array)

Найбільші за R: [10]
Строго найбільші за R: [10]


[[1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,